### ISSUE TITLE
what happens when component unmount?

### ISSUE THREAD

**Issue by dengue8830** [yojona/mafuba#4]
is there something like an unlink method? or how you prevent to call not existing refs? is some kind of clean up behavior?

**Comment by yojona** [comment]
Hi @dengue8830, you are right. Actually @e1016 proposed a solution for this a few days ago.

@e1016 can you make a PR with your solution, please? 😅

**Comment by e1016** [comment]
Sure, ASAP

**Comment by e1016** [comment]
Look for last PR @yojona

**Comment by yojona** [comment]
Merged! thank you @e1016! @dengue8830 Its done!
